### ISSUE TITLE
Regressions after last PR

### ISSUE THREAD

**Issue by maoo** [sessiontechnologies/sessiontechnologies#4]
Regressions after https://github.com/sessiontechnologies/sessiontechnologies/pull/3 was merged

Please check https://session.it/ 

1. The image background was opaque, now it's not
2. service icons are small, used to be bigger

Assigned to @barceolga

**Comment by barceolga** [comment]
Yup, I will try to resolve these issues tomorrow morning.

Olga

**Comment by barceolga** [comment]
@maoo, the Issue is solved. Please merge the newest PR from my master branch to yours. TY in advance.
